### ISSUE TITLE
Spammable Share Link

### ISSUE THREAD

**Issue by husniadil** [maman/deno-playground#7]
After typing some code and click `Share` button, it generates a new link, but when I click `Share` again without changing the content, the system still generates a new link, this is vulnerable to brute force attack and this would fill the database with junk.

**Comment by maman** [comment]
good catch!

hmm, this can be mitigated by storing the "hash" for each shared codes, and perform hash - checking first on the API-side when there's a request to share

hmm, also I should trim the source code first before performing hash-checking/storing them to db 🤔

do you have any comments/suggestions @husniadil ?

**Comment by husniadil** [comment]
@maman I think we shouldn't trim the code, better to leave it as it is.
We can try to generate code hash, for example by using sha256, and then encode the result into base64.

You may add some post processing by removing last underscore (in order to make the share-url not like suspicious).

**Comment by maman** [comment]
@husniadil the code-trimming should be necessary so it can handles spamming such as this:
```ts
console.log(Deno);
=============
console.log(Deno);<space><space>
```
for those cases, both code snippets will be resolved to a same share ID, thus further preventing persistence thrashing.

Regarding the sha256 + base64 combination, I've implemented them on #8 - feel free to check the preview deployment there 😄

**Comment by husniadil** [comment]
LGTM

**Comment by maman** [comment]
merged, and thanks for the pointers!
